min_renovasjon:
  street_name: "Kirkegårdsvegen"
  house_no: "14"
  street_code: "19500"
  county_id: "5401"
  date_format: "None"

sensor:
  - platform: min_renovasjon
    fraction_id:
      - 4
      - 23