# Require: https://github.com/jmgiaever/home-assistant-blueprints/blob/master/automation/motion_detected_lights.yaml
automation:
  - id: 'kitchen_motion_active_lights'
    alias: 'Kitchen: Motion active lights'
    use_blueprint:
      path: motion_detected_lights.yaml
      input:
        trigger_sensors:
          - binary_sensor.kitchen_motion_sensor_home_security_motion_detection
        synced_lights:
          - light.kitchen_counter_lights
          - light.kitchen_dining_table_light
          - light.kitchen_stairway_lights
        illuminance_sensors:
          - sensor.kitchen_motion_sensor_illuminance
        illuminance_threshold: 10
        after_wait_actions:
          - wait_template: "{{ is_state('input_boolean.housekeeping_mode', 'off') }}"
        wait_actions_before_dim: false
        delay: 15